package rdhs.calcularsalario;
/**
 *
 * @author User
 */
public class CalcularSalario extends javax.swing.JFrame {

    /**
     * Creates new form CalcularSalario
     */
    public CalcularSalario() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        txtPago = new javax.swing.JTextField();
        lbl_Nombre = new javax.swing.JLabel();
        lbl_Horas = new javax.swing.JLabel();
        lbl_Pago = new javax.swing.JLabel();
        lbl_Indicacion3 = new javax.swing.JLabel();
        lbl_Salario = new javax.swing.JLabel();
        lblSalario01 = new javax.swing.JLabel();
        btn_Calcular = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular_Salario");
        setBackground(new java.awt.Color(23, 21, 34));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtHoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasActionPerformed(evt);
            }
        });

        txtPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });

        lbl_Nombre.setFont(new java.awt.Font("Ink Free", 0, 12)); // NOI18N
        lbl_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Nombre.setText("Nombre:");

        lbl_Horas.setFont(new java.awt.Font("Ink Free", 0, 12)); // NOI18N
        lbl_Horas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Horas.setText("Horas trabajadas:");

        lbl_Pago.setFont(new java.awt.Font("Ink Free", 0, 12)); // NOI18N
        lbl_Pago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Pago.setText("Pago por hora:");

        lbl_Indicacion3.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        lbl_Indicacion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Indicacion3.setText("INGRESA LOS SIGUIENTES DATOS...");

        lbl_Salario.setFont(new java.awt.Font("Ink Free", 0, 12)); // NOI18N
        lbl_Salario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Salario.setText("Salario =");

        lblSalario01.setBackground(new java.awt.Color(255, 204, 204));
        lblSalario01.setForeground(new java.awt.Color(51, 0, 0));
        lblSalario01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalario01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));

        btn_Calcular.setBackground(new java.awt.Color(49, 37, 37));
        btn_Calcular.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        btn_Calcular.setForeground(new java.awt.Color(255, 255, 255));
        btn_Calcular.setText("Calcular");
        btn_Calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CalcularMouseClicked(evt);
            }
        });

        btn_Limpiar.setBackground(new java.awt.Color(65, 98, 81));
        btn_Limpiar.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        btn_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LimpiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Indicacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPago)
                                .addComponent(txtHoras)
                                .addComponent(txtNombre)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(lbl_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblSalario01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(btn_Calcular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Limpiar))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbl_Indicacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre)
                    .addComponent(lbl_Nombre))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoras)
                    .addComponent(lbl_Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPago)
                    .addComponent(lbl_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Salario, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblSalario01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Calcular)
                    .addComponent(btn_Limpiar))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasActionPerformed

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
        
    //Al cliclear el boton "Calcular"...
    private void btn_CalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalcularMouseClicked
        double horas, pago, salario, salarioNeto;
        String nombre;
        nombre = txtNombre.getText();
        horas = Double.parseDouble(txtHoras.getText());
        pago =  Double.parseDouble(txtPago.getText());
        salario = pago * horas;
        if(salario<500){
            salarioNeto = salario + (0.10*salario);
        }else{
            salarioNeto = salario + (0.15*salario);
        }
        lblSalario01.setText(String.valueOf(salarioNeto));
    }//GEN-LAST:event_btn_CalcularMouseClicked
        //Al cliclear boton "Limpiar"...
    private void btn_LimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LimpiarMouseClicked
        txtNombre.setText(null);
        txtHoras.setText(null);
        txtPago.setText(null);
        lblSalario01.setText(null);
    }//GEN-LAST:event_btn_LimpiarMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularSalario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSalario01;
    private javax.swing.JLabel lbl_Horas;
    private javax.swing.JLabel lbl_Indicacion3;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Pago;
    private javax.swing.JLabel lbl_Salario;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
